QuestPDF/QuestPDF

QuestPDF.Examples/ChartExamples.cs
QuestPDF.Examples/QuestPDF.Examples.csproj

I've added the base example from the current release of Microcharts (0.9.5.9), pretty straightforward IMO, with the only real gotcha is to ensure that IsAnimated is set to false, otherwise the chart will be rendered at the initial animation position (which will give you no visible chart).

Add simple chart example

---

QuestPDF/Helpers/PageSizes.cs

Adobe Acrobat Reader DC now shows the correct sizes for letter and legal size documents.  Fixes #63.

Tweak US Letter and Legal page sizes

---

QuestPDF/Drawing/PdfCanvas.cs
QuestPDF/Drawing/XpsCanvas.cs
QuestPDF/Helpers/WriteStreamWrapper.cs

adding a WrapperStream to support streams that not implement the Position property needed by SkiaSharp.
e.g. useful for the aspnet core response stream
fix #52

fix rendering direct to aspnet core response stream

---

QuestPDF.UnitTests/FontStyleSetTests.cs
QuestPDF/Drawing/FontManager.cs
QuestPDF/Drawing/FontStyleSet.cs

This commit allows registering multiple variants (thinkness, slant) of the same font. To do so, simply call the `RegisterFontType` method multiple times, once with each style.
Also added an overload that loads the family name from the file itself.
This means you can just put all the fonts you need in a folder and call the method with each file to load them all.
Skia's `SkFontMgr` sadly assumes all fonts will be loaded at once and while it might have support for creating new managers at runtime, I don't think SkiaSharp supports it. As such I've reimplemented the CSS font matching algorithm in C#. It also supports multiple font widths, in case QuestPDF decides to support them in the future.

FontManager: Add support for multiple variants of font families registered at runtime

---

QuestPDF.Previewer.Examples/Program.cs
QuestPDF.Previewer/DocumentPreviewerExtensions.cs
QuestPDF.Previewer/InteractiveCanvas.cs
QuestPDF.Previewer/PreviewerWindow.axaml.cs

This PR fixes 3 Issues regarding the previewer.
- Calling `ShowPreviewer` multiple times lead to an `InvalidOperationException`  when calling `AppBuilder.StartWithClassicDesktopLifetime` [Discussion](https://github.com/QuestPDF/QuestPDF/discussions/145#discussioncomment-2408643).
- Exception when Pages list is empty [Discussion](https://github.com/QuestPDF/QuestPDF/discussions/145#discussioncomment-2408643).
- Scrollbar Visibiltiy [Discussion](https://github.com/QuestPDF/QuestPDF/discussions/145#discussioncomment-2421340).

Previewer - Fix multiple small issues

---

QuestPDF/Fluent/TextExtensions.cs

Improves the exception message a tiny bit from
```
System.ArgumentException: sectionName
```
to
```
System.ArgumentException: Section name cannot be null or empty
Parameter name: sectionName
```

Use `paramName` overload of `ArgumentException`

---

readme.md

Warning	CS0618	'PageDescriptor.Background(string)' is obsolete: 'This element has been renamed since version 2022.3. Please use the PageColor method.'

replace obsolete method in readme example

---

QuestPDF/Helpers/Helpers.cs

This change avoids allocating new `Func<Element, bool>` for just a `null` check.

Convert LINQ to foreach in Helpers.VisitChildren - Reduce GC pressure

---

QuestPDF/Elements/Table/Table.cs
QuestPDF/Elements/Text/TextBlock.cs

Some blocking garbage collection is caused by newing up a `Queue` here. 
If you check the source code of the `Queue` constructor. ([find it here on GitHub](https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Queue.cs#L57)), every time a new `Queue` is instantiated, a new array is allocated with a copy of all references in `Items`. All of these arrays have to be garbage collected as well.
The `Queue` class has a `Clear()` method as well, which does not allocate a new array but instead [clears the current one](https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Queue.cs#L74) by setting all values to `null`.
This avoids excessive GC in the table benchmark.

Reduce creation of new arrays in Queue<T>

---

QuestPDF/Infrastructure/TextStyle.cs

Since `TextStyle` is copied anyway, why not have the default styles as a static variable instead of newing up one every time it is needed... This change reduces the amount of gen0 collections and boosts general performance of the table benchmark a bit.

Re-use static variable instead of method call in TextStyle

---

QuestPDF/Helpers/Helpers.cs

This is a micro-optimization by compiling regular expression into QuestPDF assembly so there's no JIT compilation when using it.
Regular expressions are usually cached, but it's not a big cache. In projects that use many RegExes themselves, the cached version may get cleared and re-populated, which incurs a small perf hit. This will make sure a compiled version is available at any time.

Micro-optimization by compiling regular expression into QuestPDF assembly

---

QuestPDF/Elements/Column.cs

I noticed the error in the 2022.08.1 release. When creating a document with more than one page, the GeneratePdf function throws a DocumentLayoutException exception with the following ElementTrace:
```
🔥 Column
---------
Available space: (Width: 14.400,000, Height: 14.400,000)
Requested space: PartialRender (Width: 0,000, Height: 0,000)
```
**To Reproduce**
```
for(int i = 0; i < 5; i++)
{
container
.Page(page =>
{
//...
});
}
```
I discovered the Column component skips the PageBreaks (the internal ones, inserted automatically between Page components) inside the function PlanLayout when called from Draw. Skipping the PageBreak, its IsRendered flag isn't set to true and then it keeps looping in the next PlanLayout call, until it triggers the DocumentLayoutException check.
The commit …

Fix DocumentLayoutException when creating a document with more than one page

---

QuestPDF.Previewer/PreviewerWindowViewModel.cs

Since the documentation was reworked the route for the `API Reference` has changed.
However the `Show documentation` button still links to the old route -> 404.

Fix documentation link for previewer

---

QuestPDF.Examples/TextBenchmark.cs
QuestPDF.Examples/TextExamples.cs
QuestPDF.Previewer/QuestPDF.Previewer.csproj
QuestPDF/Drawing/DocumentGenerator.cs
QuestPDF/Drawing/Exceptions/DocumentDrawingException.cs
QuestPDF/Drawing/FontManager.cs
QuestPDF/Drawing/TextMeasurement.cs
QuestPDF/Drawing/TextShaper.cs
QuestPDF/Elements/Dynamic.cs
QuestPDF/Elements/Text/FontFallback.cs
QuestPDF/Elements/Text/Items/TextBlockSpan.cs
QuestPDF/Elements/Text/TextBlock.cs
QuestPDF/Fluent/TextExtensions.cs
QuestPDF/Fluent/TextSpanDescriptorExtensions.cs
QuestPDF/Fluent/TextStyleExtensions.cs
QuestPDF/Infrastructure/TextStyle.cs
QuestPDF/Infrastructure/TextStyleManager.cs
QuestPDF/Previewer/PreviewerService.cs
QuestPDF/QuestPDF.csproj
QuestPDF/Resources/ReleaseNotes.txt
QuestPDF/Settings.cs

1) Implemented font-fallback algorithm
2) Introduced new Settings API,
3) Improved rendering performance by 50% (in text-heavy documents),
4) Significantly reduced memory allocation cost for TextStyle objects,
5) Implemented optional checking if all font glyphs are available,
6) Minor text-rendering optimizations.
1) Text is one of the fundamental content blocks in all documents.
2) For every Text element, new TextStyle object is created, leading to millions of instances over time.
3) TextStyle objects are heavily mutated by parent styles and global styles. To avoid collisions, it often leads to double of TextStyle elements.
4) TextStyle is heavy, constains multiple references and many primitivies.
5) TextStyle is commonly used as dictionary key.
During document generation, thousands of …

2022.9 Release

---

QuestPDF.Examples/DefaultTextStyleExamples.cs
QuestPDF.Examples/DynamicOptimizedExample.cs
QuestPDF.Examples/DynamicSimpleTableExample.cs
QuestPDF.Examples/TableExamples.cs
QuestPDF.Examples/TextExamples.cs
QuestPDF/Fluent/TextExtensions.cs

In addition to reminding us to pass numbers in the right culture, we also keep our API safe from unexpected values. For example
`dotnet fsi example.fsx`
```fs
#r "nuget: QuestPDF, 2022.9.0"
open QuestPDF.Fluent
open QuestPDF.Helpers
let filename = "hello.pdf"
Document
.Create(fun container ->
container.Page(fun page ->
page.Size(PageSizes.A10);
page.Content()
.AlignCenter()
.Text(fun x ->
x.Span("Page ") |> ignore
x.CurrentPageNumber()) |> ignore)
|> ignore)
.GeneratePdf(filename)
System.Diagnostics.Process.Start("explorer", filename) |> ignore
```
Closes #257

Replace type parameter text for Text

---

QuestPDF.Examples/TextExamples.cs
QuestPDF/Drawing/TextShaper.cs
QuestPDF/Fluent/TextSpanDescriptorExtensions.cs
QuestPDF/Fluent/TextStyleExtensions.cs
QuestPDF/Infrastructure/TextStyle.cs
QuestPDF/Infrastructure/TextStyleManager.cs

For further info see #393.
This PR implements letter spacing for text, similar to this [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing).
Sample code:
```csharp
container
.Text("Some text with letter spacing")
.LetterSpacing(2.0);
```
Showcase:

Letter spacing

---

Source/QuestPDF/Elements/Text/FontFallback.cs

The fix for https://github.com/QuestPDF/QuestPDF/issues/504

fix glyph check in FontFallback.MatchFallbackOption

---

Source/QuestPDF.Examples/ContentDirectionExamples.cs
Source/QuestPDF.Examples/DynamicOptimizedExample.cs
Source/QuestPDF.Previewer/InteractiveCanvas.cs
Source/QuestPDF.Previewer/PreviewerWindowViewModel.cs
Source/QuestPDF.ReportSample/Layouts/SectionTemplate.cs
Source/QuestPDF.ReportSample/Layouts/TableOfContentsTemplate.cs
Source/QuestPDF.UnitTests/DynamicImageTests.cs
Source/QuestPDF.UnitTests/FontStyleSetTests.cs
Source/QuestPDF.UnitTests/ImageTests.cs
Source/QuestPDF/Drawing/Proxy/CacheProxy.cs
Source/QuestPDF/Elements/Inlined.cs
Source/QuestPDF/Elements/Table/Table.cs
Source/QuestPDF/Previewer/PreviewerService.cs

These methods aren't part of any public API, and the `static` keyword gives us certain guarantees

`private` methods that don't access any instance members were made `static`

---

Source/QuestPDF/Drawing/DocumentGenerator.cs

Fixed the link error to the License configuration documentation.

Fixed license configuration links in ValidateLicense exception message

---

Source/QuestPDF/Fluent/RowExtensions.cs

This brings it in line with column spacing and allows the user to specify row spacing in units other than points.

Add units to row spacing

---

Source/QuestPDF/Previewer/PreviewerExtensions.cs

Add a new optional parameter for passing CancellationToken to `ShowInPreviewerAsync` method.
Fixes #713

Add CancellationToken parameter to ShowInPreviewerAsync

---

Source/QuestPDF/Skia/SkNativeDependencyProvider.cs

Added a fix for finding native files (icudtl.dat & QuestPdfSkia.dll)
In a .net 4.8 application, the baseDirectory is not the bin folder.
In response to https://github.com/QuestPDF/QuestPDF/discussions/622#discussioncomment-8695313

Fix: Update logic to find native files (icudtl.dat & QuestPdfSkia.dll)

---

Source/QuestPDF/Fluent/DocumentOperation.cs

Added a line to trim the leading period and convert the file extension to lowercase before looking it up in the MIME type conversion table. This improves the accuracy of MIME type detection for attachments with varying file extension formats.
Fixes #1119

Standardize file extension for MIME type detection

---

Source/QuestPDF/Fluent/ElementExtensions.cs

Fixes an url to the documentation in the canvas deprecated message

Fix incorrect url in obsolete message
